version: '3.8'

services:
  app:
    container_name: weather-web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_URL: ${WEATHER_API_URL}
      SPRING_PROFILES_ACTIVE: prod
    command: ["java", "-jar", "/app/weather-web-app.jar"]